In [50]:
# Load the basic data wrangling modules
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'1.1.1'

In [3]:
np.__version__

'1.19.3'

In [6]:
# List of two a and b
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [7]:
a + b

array([5, 7, 9])

In [8]:
a - b

array([-3, -3, -3])

In [9]:
a * b

array([ 4, 10, 18])

In [10]:
a / b

array([0.25, 0.4 , 0.5 ])

In [11]:
text = "1,2,3,4,5,6,7"

In [16]:
df = pd.DataFrame({
    "name": ["john", "mike", "tom", "hardy", "jack"],
    "age": [25, 40, 34, 23, 21],
    "gender": ("Male", "Male", "Male", "Female", "Male") 
})

In [17]:
df

name  age  gender
0   john   25    Male
1   mike   40    Male
2    tom   34    Male
3  hardy   23  Female
4   jack   21    Male

In [32]:
for record in df.values:
    print(record)

['john' 25 'Male']
['mike' 40 'Male']
['tom' 34 'Male']
['hardy' 23 'Female']
['jack' 21 'Male']


In [34]:
def convert(n):
    if n == 'john':
        return 0
    if n == 'mike':
        return 1
    if n == 'tom':
        return 2
    if n == 'hardy':
        return 3
    if n == 'jack':
        return 4
    

In [35]:
convert('tom')

2

In [37]:
df['cname'] = df['name'].apply(convert)

In [39]:
def convert_gender(n):
    if n == 'Male':
        return 1
    if n == 'Female':
        return 0

In [41]:
df['cgender'] = df['gender'].apply(convert_gender)

In [44]:
df[['age', 'cname', 'cgender']].values

array([[25,  0,  1],
       [40,  1,  1],
       [34,  2,  1],
       [23,  3,  0],
       [21,  4,  1]])

In [45]:
df

name  age  gender  cname  cgender
0   john   25    Male      0        1
1   mike   40    Male      1        1
2    tom   34    Male      2        1
3  hardy   23  Female      3        0
4   jack   21    Male      4        1

In [46]:
df

name  age  gender  cname  cgender
0   john   25    Male      0        1
1   mike   40    Male      1        1
2    tom   34    Male      2        1
3  hardy   23  Female      3        0
4   jack   21    Male      4        1

In [47]:
df1 = pd.DataFrame({
    "john": [1, 0, 0, 0, 0],
    "mike": [0, 1, 0, 0, 0],
    "tom" : [0, 0, 1, 0, 0],
    "hardy": [0, 0, 0, 1, 0],
    "jack": [0 ,0 ,0,0,1],
    "age": [25, 40, 34, 23, 21],
    "male": [1, 1, 1, 0, 1],
    "female": [0, 0, 0, 1, 0]
})

In [48]:
df1

john  mike  tom  hardy  jack  age  male  female
0     1     0    0      0     0   25     1       0
1     0     1    0      0     0   40     1       0
2     0     0    1      0     0   34     1       0
3     0     0    0      1     0   23     0       1
4     0     0    0      0     1   21     1       0

In [51]:
df

name  age  gender  cname  cgender
0   john   25    Male      0        1
1   mike   40    Male      1        1
2    tom   34    Male      2        1
3  hardy   23  Female      3        0
4   jack   21    Male      4        1

In [59]:
data = pd.DataFrame({
    
    "datetime": ['2020/05/01-01:10:00', '2020/05/02-10:10:20', '2020/05/03-12:10:00', '2020/05/04-05:01:00', '2020/05/05-06:01:01'],
    "name": ['Mr. John', 'Mr. Mike', 'Miss.Jenny', 'Dr.Hardy', 'Prof.Jack'],
    "height": [150, 140, np.nan, 164, 170],
    "weight": [65.5, 50.5, 70.2, 80, 90],
    "age": [np.nan, 40, 42, 55, 60],
    "gender": ['male', 'male', 'female', np.nan, 'male'],
    "is_survived": [1, 1, 0, 1, 0]
})


In [60]:
data

datetime        name  height  weight   age  gender  is_survived
0  2020/05/01-01:10:00    Mr. John   150.0    65.5   NaN    male            1
1  2020/05/02-10:10:20    Mr. Mike   140.0    50.5  40.0    male            1
2  2020/05/03-12:10:00  Miss.Jenny     NaN    70.2  42.0  female            0
3  2020/05/04-05:01:00    Dr.Hardy   164.0    80.0  55.0     NaN            1
4  2020/05/05-06:01:01   Prof.Jack   170.0    90.0  60.0    male            0

## Feature Engineering 
- Handling datetime values
- Handling missing values in categorical variable
- Handling missing values in continuous variable
- Encoding categorical variable
- Scaling and Standardizing continuous variable

## Handling Datetime Feature

In [61]:
a = "2020/05/01-01:10:00"

In [62]:
type(a)

str

In [64]:
date, time = a.split('-')

In [65]:
date

'2020/05/01'

In [66]:
time

'01:10:00'

In [67]:
yyyy, mm, dd = date.split('/')

In [71]:
print('Year', yyyy)
print('Month', mm)
print('Year', dd)

Year 2020
Month 05
Year 01


In [72]:
hh, mi, sec = time.split(':')

In [73]:
print("Hour", hh)
print("Min", mi)
print("Sec", sec)

Hour 01
Min 10
Sec 00


In [76]:
def split_datetime(d):
    # Split the `2020/05/01-01:10:00` using `-` and 
    # get date and time seperated
    date, time = d.split('-')
        
    # Split the `date` variable in `yyyy, mm, dd`
    yyyy, mm, dd = date.split('/')
    
    # Split the `time` variable into `hh,mi,sec` 
    hh, mi, sec = time.split(':')
    
    return {
        'year': int(yyyy),
        'month': int(mm),
        'day': int(dd),
        'hour': int(hh),
        'minute': int(mi),
        'second': int(sec)
    }

In [99]:
split_datetime(a)

{'year': 2020, 'month': 5, 'day': 1, 'hour': 1, 'minute': 10, 'second': 0}

In [101]:
data.drop('sample', axis=1, inplace=True)

In [102]:
data

datetime        name  height  weight   age  gender  is_survived
0  2020/05/01-01:10:00    Mr. John   150.0    65.5   NaN    male            1
1  2020/05/02-10:10:20    Mr. Mike   140.0    50.5  40.0    male            1
2  2020/05/03-12:10:00  Miss.Jenny     NaN    70.2  42.0  female            0
3  2020/05/04-05:01:00    Dr.Hardy   164.0    80.0  55.0     NaN            1
4  2020/05/05-06:01:01   Prof.Jack   170.0    90.0  60.0    male            0

In [106]:
for d in data['datetime']:
    print("Day", split_datetime(d)['day'])

Day 1
Day 2
Day 3
Day 4
Day 5


In [114]:
# List comprehension
data['day'] = [split_datetime(d)['day'] for d in data['datetime']]

In [115]:
data

datetime        name  height  weight   age  gender  is_survived  \
0  2020/05/01-01:10:00    Mr. John   150.0    65.5   NaN    male            1   
1  2020/05/02-10:10:20    Mr. Mike   140.0    50.5  40.0    male            1   
2  2020/05/03-12:10:00  Miss.Jenny     NaN    70.2  42.0  female            0   
3  2020/05/04-05:01:00    Dr.Hardy   164.0    80.0  55.0     NaN            1   
4  2020/05/05-06:01:01   Prof.Jack   170.0    90.0  60.0    male            0   

   day  
0    1  
1    2  
2    3  
3    4  
4    5

In [116]:
data['month'] = [split_datetime(d)['month'] for d in data['datetime']]
data['year'] = [split_datetime(d)['year'] for d in data['datetime']]
data['hour'] = [split_datetime(d)['hour'] for d in data['datetime']]
data['minute'] = [split_datetime(d)['minute'] for d in data['datetime']]
data['second'] = [split_datetime(d)['second'] for d in data['datetime']]

In [117]:
data

datetime        name  height  weight   age  gender  is_survived  \
0  2020/05/01-01:10:00    Mr. John   150.0    65.5   NaN    male            1   
1  2020/05/02-10:10:20    Mr. Mike   140.0    50.5  40.0    male            1   
2  2020/05/03-12:10:00  Miss.Jenny     NaN    70.2  42.0  female            0   
3  2020/05/04-05:01:00    Dr.Hardy   164.0    80.0  55.0     NaN            1   
4  2020/05/05-06:01:01   Prof.Jack   170.0    90.0  60.0    male            0   

   day  month  year  hour  minute  second  
0    1      5  2020     1      10       0  
1    2      5  2020    10      10      20  
2    3      5  2020    12      10       0  
3    4      5  2020     5       1       0  
4    5      5  2020     6       1       1

In [118]:
# Lets drop the `datetime` column forever
data.drop('datetime', axis=1, inplace=True)

In [119]:
data

name  height  weight   age  gender  is_survived  day  month  year  \
0    Mr. John   150.0    65.5   NaN    male            1    1      5  2020   
1    Mr. Mike   140.0    50.5  40.0    male            1    2      5  2020   
2  Miss.Jenny     NaN    70.2  42.0  female            0    3      5  2020   
3    Dr.Hardy   164.0    80.0  55.0     NaN            1    4      5  2020   
4   Prof.Jack   170.0    90.0  60.0    male            0    5      5  2020   

   hour  minute  second  
0     1      10       0  
1    10      10      20  
2    12      10       0  
3     5       1       0  
4     6       1       1

## Create Profession Column Using Name

In [121]:
a = 'Mr. John'

In [124]:
def extract_prof(d):
    prof, name = d.split('.')
    return prof

In [125]:
extract_prof(a)

'Mr'

In [126]:
data['profession'] = data['name'].apply(extract_prof)

In [127]:
data

name  height  weight   age  gender  is_survived  day  month  year  \
0    Mr. John   150.0    65.5   NaN    male            1    1      5  2020   
1    Mr. Mike   140.0    50.5  40.0    male            1    2      5  2020   
2  Miss.Jenny     NaN    70.2  42.0  female            0    3      5  2020   
3    Dr.Hardy   164.0    80.0  55.0     NaN            1    4      5  2020   
4   Prof.Jack   170.0    90.0  60.0    male            0    5      5  2020   

   hour  minute  second profession  
0     1      10       0         Mr  
1    10      10      20         Mr  
2    12      10       0       Miss  
3     5       1       0         Dr  
4     6       1       1       Prof

In [128]:
# Lets remove `name` columns
data.drop('name', axis=1, inplace=True)

In [129]:
data

height  weight   age  gender  is_survived  day  month  year  hour  minute  \
0   150.0    65.5   NaN    male            1    1      5  2020     1      10   
1   140.0    50.5  40.0    male            1    2      5  2020    10      10   
2     NaN    70.2  42.0  female            0    3      5  2020    12      10   
3   164.0    80.0  55.0     NaN            1    4      5  2020     5       1   
4   170.0    90.0  60.0    male            0    5      5  2020     6       1   

   second profession  
0       0         Mr  
1      20         Mr  
2       0       Miss  
3       0         Dr  
4       1       Prof

## Handling Missing Value In Continuous 
- Replace with mean
- Replace with median

In [135]:
data['height'].fillna(data['height'].mean(), inplace=True)

In [136]:
data

height  weight   age  gender  is_survived  day  month  year  hour  minute  \
0   150.0    65.5   NaN    male            1    1      5  2020     1      10   
1   140.0    50.5  40.0    male            1    2      5  2020    10      10   
2   156.0    70.2  42.0  female            0    3      5  2020    12      10   
3   164.0    80.0  55.0     NaN            1    4      5  2020     5       1   
4   170.0    90.0  60.0    male            0    5      5  2020     6       1   

   second profession  
0       0         Mr  
1      20         Mr  
2       0       Miss  
3       0         Dr  
4       1       Prof

## Handling Missing value in Discrete

In [139]:
data['age'].fillna(data['age'].median(), inplace=True)

In [140]:
data

height  weight   age  gender  is_survived  day  month  year  hour  minute  \
0   150.0    65.5  48.5    male            1    1      5  2020     1      10   
1   140.0    50.5  40.0    male            1    2      5  2020    10      10   
2   156.0    70.2  42.0  female            0    3      5  2020    12      10   
3   164.0    80.0  55.0     NaN            1    4      5  2020     5       1   
4   170.0    90.0  60.0    male            0    5      5  2020     6       1   

   second profession  
0       0         Mr  
1      20         Mr  
2       0       Miss  
3       0         Dr  
4       1       Prof

## Handling Missing Categorical Variable

In [142]:
data['gender'].isna().any()

True

In [145]:
data['gender'].describe()

count        4
unique       2
top       male
freq         3
Name: gender, dtype: object

In [158]:
data['gender'].fillna(data['gender'].mode(), inplace=True)

In [159]:
data

height  weight   age  gender  is_survived  day  month  year  hour  minute  \
0   150.0    65.5  48.5    male            1    1      5  2020     1      10   
1   140.0    50.5  40.0    male            1    2      5  2020    10      10   
2   156.0    70.2  42.0  female            0    3      5  2020    12      10   
3   164.0    80.0  55.0    male            1    4      5  2020     5       1   
4   170.0    90.0  60.0    male            0    5      5  2020     6       1   

   second profession  
0       0         Mr  
1      20         Mr  
2       0       Miss  
3       0         Dr  
4       1       Prof

### Create New `BMI` column using `weight` and `height`

````
    Formula to calculate the BMI value
    round(weight / (height * height), 2)
````

In [160]:
def calculate_bmi(weight, height):
    return round(weight / (height * height), 2)

In [163]:
calculate_bmi(70.5, 150.0)

0.0

In [174]:
data['bmi'] = [calculate_bmi(d['weight'], d['height']) for idx, d in data.iterrows()]

In [175]:
data

height  weight   age  gender  is_survived  day  month  year  hour  minute  \
0   150.0    65.5  48.5    male            1    1      5  2020     1      10   
1   140.0    50.5  40.0    male            1    2      5  2020    10      10   
2   156.0    70.2  42.0  female            0    3      5  2020    12      10   
3   164.0    80.0  55.0    male            1    4      5  2020     5       1   
4   170.0    90.0  60.0    male            0    5      5  2020     6       1   

   second profession  bmi  
0       0         Mr  0.0  
1      20         Mr  0.0  
2       0       Miss  0.0  
3       0         Dr  0.0  
4       1       Prof  0.0

In [176]:
calculate_bmi(85, 5.8)

2.53

In [179]:
enc_data = pd.get_dummies(data[['gender', 'profession']])

In [182]:
final_df = pd.concat([data, enc_data], axis=1)

In [183]:
final_df

height  weight   age  gender  is_survived  day  month  year  hour  minute  \
0   150.0    65.5  48.5    male            1    1      5  2020     1      10   
1   140.0    50.5  40.0    male            1    2      5  2020    10      10   
2   156.0    70.2  42.0  female            0    3      5  2020    12      10   
3   164.0    80.0  55.0    male            1    4      5  2020     5       1   
4   170.0    90.0  60.0    male            0    5      5  2020     6       1   

   second profession  bmi  gender_female  gender_male  profession_Dr  \
0       0         Mr  0.0              0            1              0   
1      20         Mr  0.0              0            1              0   
2       0       Miss  0.0              1            0              0   
3       0         Dr  0.0              0            1              1   
4       1       Prof  0.0              0            1              0   

   profession_Miss  profession_Mr  profession_Prof  
0                0              1                0  
1                0              1                0  
2                1              0                0  
3                0              0                0  
4                0              0                1

In [184]:
final_df.drop(['gender', 'profession'], axis=1, inplace=True)

In [188]:
final_df.dtypes

height             float64
weight             float64
age                float64
is_survived          int64
day                  int64
month                int64
year                 int64
hour                 int64
minute               int64
second               int64
bmi                float64
gender_female        uint8
gender_male          uint8
profession_Dr        uint8
profession_Miss      uint8
profession_Mr        uint8
profession_Prof      uint8
dtype: object